### ISSUE TITLE
Users can belong to more than one office

### ISSUE THREAD

**Issue by mlab817** [dapmsipd/pips#154] opened 2023-12-13 01:03 UTC
As experienced during the updating, some users were members of more than one office:

1. One user was transferred from BAFS to FDC. 
2. One user was the level 2 encoder of three offices.

The workaround was to ask the user to create one account per office but this is exhausting and confusing for the user.

For number one, this was solved by removing the user_id tagging from the PAP. Initially, there was a user_id tagging in the project that allows the user to view it whether or not they belong to the office or not. So number 1 is no longer a problem.

The proposed solution is to allow a user to belong to more than one office and a specific role for that office. In the frontend, to avoid confusion for the user, it is also possible to allow them to toggle between offices a la Facebook "Switch Account" feature. Whether or not this feature will be worked on will depend on the projected number of users that may end up being in the same boat.

**Comment by daipd** [comment] 2023-12-15 01:49
Duplicate of https://github.com/dapmsipd/pips/issues/118

**Closed as completed by daipd** 2023-12-15 01:49 UTC
Labels: duplicate, enhancement, backend
